CREATE TABLE IF NOT EXISTS `champions` (
`Nome` varchar(25) PRIMARY KEY,
`Classe_Primaria` varchar(25),
`Classe_Secundaria` varchar(25)
);

INSERT INTO champions VALUES
('Aatrox','Lutador',''),
('Ahri','Mago','Assassino'),
('Akali','Assassino',''),
('Alistar','Tanque',''),
('Amumu','Tanque','Mago'),
('Anivia','Mago','Suporte'),
('Annie','Mago',''),
('Aphelios','Atirador',''),
('Ashe','Atirador','Suporte'),
('Aurelion Sol','Mago',''),
('Azir','Mago','Atirador'),
('Bardo','Suporte','Mago'),
('Blitzcrank','Tanque','Lutador'),
('Brand','Mago',''),
('Braum','Suporte','Tanque'),
('Caitlyn','Atirador',''),
('Camille','Lutador','Tanque'),
('Cassiopeia','Mago',''),
('ChoGath','Tanque','Mago'),
('Corki','Atirador',''),
('Darius','Lutador','Tanque'),
('Diana','Lutador','Mago'),
('Dr Mundo','Lutador','Tanque'),
('Draven','Atirador',''),
('Ekko','Assassino','Lutador'),
('Elise','Mago','Lutador'),
('Evelynn','Assassino','Mago'),
('Ezreal','Atirador','Mago'),
('Fiddlesticks','Mago','Suporte'),
('Fiora','Lutador','Assassino'),
('Fizz','Assassino','Lutador'),
('Galio','Tanque','Mago'),
('Gangplank','Lutador','Suporte'),
('Garen','Lutador','Tanque'),
('Gnar','Lutador','Tanque'),
('Gragas','Lutador','Mago'),
('Graves','Atirador',''),
('Hecarim','Lutador','Tanque'),
('Heimerdinger','Mago','Suporte'),
('Illaoi','Lutador','Tanque'),
('Irelia','Lutador','Assassino'),
('Ivern','Suporte','Mago'),
('Janna','Suporte','Mago'),
('Jarvan IV','Tanque','Lutador'),
('Jax','Lutador','Assassino'),
('Jayce','Lutador','Atirador'),
('Jhin','Atirador','Assassino'),
('Jinx','Atirador',''),
('Kalista','Atirador',''),
('Karma','Mago','Suporte'),
('Karthus','Mago',''),
('Kassadin','Assassino','Mago'),
('Katarina','Assassino','Mago'),
('Kayle','Lutador','Suporte'),
('Kayn','Lutador',''),
('Kennen','Mago','Atirador'),
('KhaZix','Assassino',''),
('Kindred','Atirador',''),
('Kled','Lutador','Tanque'),
('KogMaw','Atirador','Mago'),
('LeBlanc','Assassino','Mago'),
('Lee Sin','Lutador','Assassino'),
('Leona','Tanque','Suporte'),
('Lillia','Lutador',''),
('Lissandra','Mago',''),
('Lucian','Atirador',''),
('Lulu','Suporte','Mago'),
('Lux','Mago','Suporte'),
('Malphite','Tanque','Lutador'),
('Malzahar','Mago','Assassino'),
('Maokai','Tanque','Mago'),
('Master Yi','Assassino','Lutador'),
('Miss Fortune','Atirador',''),
('Mordekaiser','Lutador','Mago'),
('Morgana','Mago','Controlador'),
('Nami','Suporte','Mago'),
('Nasus','Lutador','Tanque'),
('Nautilus','Tanque','Lutador'),
('Neeko','Mago',''),
('Nidalee','Assassino','Lutador'),
('Nocturne','Assassino','Lutador'),
('Nunu','Suporte','Lutador'),
('Olaf','Lutador','Tanque'),
('Orianna','Mago','Suporte'),
('Ornn','Tanque',''),
('Pantheon','Lutador','Assassino'),
('Poppy','Tanque','Lutador'),
('Pyke','Suporte',''),
('Qiyana','Assassino',''),
('Quinn','Atirador','Lutador'),
('Rakan','Controller',''),
('Rammus','Tanque','Lutador'),
('RekSai','Lutador',''),
('Renekton','Lutador','Tanque'),
('Rengar','Assassino','Lutador'),
('Riven','Lutador','Assassino'),
('Rumble','Lutador','Mago'),
('Ryze','Mago','Lutador'),
('Sejuani','Tanque','Lutador'),
('Senna','Suporte',''),
('Shaco','Assassino',''),
('Shen','Tanque','Lutador'),
('Shyvana','Lutador','Tanque'),
('Singed','Tanque','Lutador'),
('Sion','Lutador','Mago'),
('Sivir','Atirador',''),
('Skarner','Lutador','Tanque'),
('Sona','Suporte','Mago'),
('Soraka','Suporte','Mago'),
('Swain','Mago','Lutador'),
('Sylas','Lutador','Mago'),
('Syndra','Mago','Suporte'),
('Tahm Kench','Suporte','Tanque'),
('Taliyah','Mago','Suporte'),
('Talon','Assassino','Lutador'),
('Taric','Suporte','Lutador'),
('Teemo','Atirador','Assassino'),
('Thresh','Suporte','Lutador'),
('Tristana','Atirador','Assassino'),
('Trundle','Lutador','Tanque'),
('Tryndamere','Lutador','Assassino'),
('Twisted Fate','Mago',''),
('Twitch','Atirador','Assassino'),
('Udyr','Lutador','Tanque'),
('Urgot','Atirador','Tanque'),
('Varus','Atirador','Mago'),
('Vayne','Atirador','Assassino'),
('Veigar','Mago',''),
('VelKoz','Mago',''),
('Vi','Lutador','Assassino'),
('Viktor','Mago',''),
('Vladimir','Mago','Tanque'),
('Volibear','Lutador','Tanque'),
('Warwick','Lutador','Tanque'),
('Wukong','Lutador','Tanque'),
('Xayah','Atirador',''),
('Xerath','Mago','Assassino'),
('Xin Zhao','Lutador','Assassino'),
('Yasuo','Lutador','Assassino'),
('Yone','Assassino',''),
('Yorick','Lutador','Mago'),
('Yuumi','Suporte',''),
('Zac','Tanque','Lutador'),
('Zed','Assassino','Lutador'),
('Ziggs','Mago',''),
('Zilean','Suporte','Mago'),
('Zoe','Mago','');
